app/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_bootstrap import Bootstrap 
from app.main import bp as main

bootstrap = Bootstrap()
mail = Mail()

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    mail.init_app(app)
    bootstrap.init_app(app)
    app.register_blueprint(main)
    return app

app = create_app()

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import os, sys
import redis
from flask import current_app
from app.config import *
from flask import request, redirect, render_template, flash, Blueprint, g
from werkzeug.utils import secure_filename
from app.main import bp
from rq import Queue, push_connection, pop_connection
from wtforms import Form, validators, TextField, FloatField, FileField
ALLOWED_EXTENSIONS = set(['mp4', 'mkv'])


def get_redis_connection():
    redis_connection = getattr(g, '_redis_connection', None)
    if redis_connection is None:
        redis_url = current_app.config['REDIS_URL']
        redis_connection = g._redis_connection = redis.from_url(redis_url)
    return redis_connection


@bp.before_request
def push_rq_connection():
    push_connection(get_redis_connection())


@bp.teardown_request
def pop_rq_connection(exception=None):
    pop_connection()


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

class ReusableForm(Form):
    emailID = TextField('Email Address', validators=[validators.required()])
    mod_start = FloatField('Moderator Start Time (s)', validators=[validators.required()])
    mod_end = FloatField('Moderator Start Time (s)', validators=[validators.required()])
    ipfile = FileField('File', validators=[validators.required()])
    
@bp.route('/', methods=['GET', 'POST'])
def index():
    form = ReusableForm(request.form)

    if request.method == 'POST':
        email = request.form['email']
        mod_start = request.form['start']
        mod_end = request.form['end']
        
        if "inputfile" not in request.files:
            flash('Please select a file')
            return render_template("upload.html", form=form)
        
        if mod_start >= mod_end:
            flash('Please enter valid times')
            return render_template("upload.html", form=form)

        if email=="":
            flash('Please enter an email address') 
            return render_template("upload.html", form=form)
        

        ipfile = request.files['inputfile']
        if ipfile:
            filename = secure_filename(ipfile.filename)
            filepath = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            ipfile.save(filepath)
            flash("File {} has been uploaded successfully, please wait for email with inference details".format(filename))
            job_queue = Queue()
            job = job_queue.enqueue('app.process_files.run_SAD', args=(filepath, email, mod_start, mod_end), timeout=current_app.config['JOB_TIMEOUT'] )
            return redirect(request.url)
    return render_template("upload.html", form=form) 

app/templates/base.html
{%- extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {{super()}}
{% endblock %}

{% block styles %}
  {{super()}}
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}Speaking Time Estimation{% endblock %}

{% block navbar %}
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--img class="navbar-brand" src="../../static/logo.png"-->
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Speaking Time Estimation</a>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container" id="mainContent">
    {{utils.flashed_messages(container=False, dismissible=True)}}
    {% block main %}{% endblock %}
  </div>
{% endblock %}

app/templates/upload.html
 {%- extends "base.html" %}
 {% import "bootstrap/wtf.html" as wtf %}
 
 {% with messages = get_flashed_messages() %}
	{% if messages %}
		<ul>
			{% for message in messages %}
			<li>{{ message }} </li>
			{% endfor %}
		</ul>
	{% endif %}
 {% endwith %} 

 {% block main %}
    <div class="panel panel-default">
        <div class="panel-heading"> Select file to process </div>
        <div class="panel-body">
            <div class="col-md-12">
			<form method=post enctype=multipart/form-data>
                 {{ form.csrf }}
                 <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
                </div>

				<div class="row">
					<div class="col-md-6">
				      <label for="start">Moderator Start Time (s)</label>
					  <input type="number" step="any" class="form-control" id="start" name="start" placeholder="0.0">
					</div>
					<div class="col-md-6">
				      <label for="end">Moderator End Time (s)</label>
					  <input type="number" step="any" class="form-control" id="end" name="end" placeholder="3.5">
					</div>
				  </div>
				<div class="custom-file">
					<input type="file" accept=".mp4,.mkv" class="custom-file-input" id="inputfile" name="inputfile">
					<label class="custom-file-label" for="inputfile"></label>
				  </div>
				<input class="btn btn-primary" type="submit" value="Submit">
		   </form>


           </div>
       </div>
       </div>
   </div>    

 {% endblock %}

app/templates/upload_bu.html
 <!doctype html>
 <title>Upload new file</title>
 <body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }} </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}   
 <h1>Upload new file</h1>
 </body>
 <form method=post enctype=multipart/form-data>
 <input type=file name=file>
 <input type=submit value=Upload>
 </form> 